main:
	cat README.md | sed -e "s/2 Challenge/3 Solution/" > ../01_03-solution-deploy-a-jenkins-server/README.md
	cp ./jenkins-server-automated-installation.sh ../01_03-solution-deploy-a-jenkins-server/
